version: "3.9"

services:
  mempool-watcher:
    build:
      context: .
    container_name: mempool-watcher
    restart: unless-stopped
    env_file: .env
    volumes:
      - watcher_data:/data
    extra_hosts:
      - "umbrel.local:192.168.1.79"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  watcher_data:
    driver: local